### ISSUE TITLE
TypeError: Found non-callable @@iterator

### ISSUE THREAD

**Issue by waraoni** [nolimits4web/Dom7#53]
A way to reproduce:

`
import { $ } from 'dom7';
$('div').map(element => console.log(element));
`

dom7 version 4.0.2

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
